In [5]:
import torch.nn as nn
import torch

In [6]:
fc = nn.Linear(3, 2)

In [7]:
fc.weight

Parameter containing:
tensor([[ 0.3404, -0.5235, -0.1125],
        [-0.5231, -0.5746, -0.2030]], requires_grad=True)

In [8]:
fc.bias

Parameter containing:
tensor([ 0.2854, -0.1835], requires_grad=True)

In [9]:
torch.manual_seed(1)

In [10]:
fc = nn.Linear(3, 2)
fc.weight

Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119],
        [ 0.2710, -0.5435,  0.3462]], requires_grad=True)

In [11]:
fc.bias

Parameter containing:
tensor([-0.1188,  0.2937], requires_grad=True)

In [12]:
x = torch.tensor([[1, 2, 3]])
x

tensor([[1, 2, 3]])

In [13]:
type(x)

torch.Tensor

In [14]:
u = fc(x)

RuntimeError: expected scalar type Float but found Long

In [16]:
x.dtype

torch.int64

In [17]:
x = torch.tensor([[1, 2, 3]], dtype=torch.float32)
x

tensor([[1., 2., 3.]])

In [18]:
x.dtype

torch.float32

In [19]:
u = fc(x)
u

tensor([[-0.6667,  0.5164]], grad_fn=<AddmmBackward0>)

In [20]:
import torch.nn.functional as F

#ReLU function
h = F.relu(u)
h

tensor([[0.0000, 0.5164]], grad_fn=<ReluBackward0>)

In [22]:
# Fixed random number seed
torch.manual_seed(1)

# definition of input values
x = torch.tensor([[1, 2, 3]], dtype=torch.float32)
x

tensor([[1., 2., 3.]])

In [23]:
# definition of fully connected layer
fc1 = nn.Linear(3, 2)
fc2 = nn.Linear(2, 1)

# linear transformation
u1 = fc1(x)
u1

tensor([[-0.6667,  0.5164]], grad_fn=<AddmmBackward0>)

In [24]:
# non-linear transformation
h1 = F.relu(u1)

# linear transformation
y = fc2(h1)
y

tensor([[0.1514]], grad_fn=<AddmmBackward0>)

In [25]:
t = torch.tensor([[1]], dtype=torch.float32)
t

tensor([[1.]])

In [28]:
loss = F.mse_loss(t, y)
loss

tensor(0.7201, grad_fn=<MseLossBackward0>)